In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('../output/Jobkorea_0725_1.xlsx', index_col=0)
df.head()

,title,job,cname,duties,skills,preference,welfare,loc,rec type,url,keyword
0,비즈테크아이 채용 - [LG그룹] BI/DW데이터 엔지니어 채용 | 잡코리아,데이터 엔지니어,㈜비즈테크아이,NaN,NaN,NaN,NaN,서울 > 마포구,경력,https://www.jobkorea.co.kr//Recruit/GI_Read/39...,"IT분야 직무채용관, QA·테스터·검증, Windows, 리눅스, DBA·데이터베이..."
1,웅진씽크빅 채용 - [웅진씽크빅] 정규직 데이터 엔지니어 채용 | 잡코리아,데이터 엔지니어,㈜웅진씽크빅,NaN,NaN,NaN,NaN,서울 > 중구,경력(3년이상),https://www.jobkorea.co.kr//Recruit/GI_Read/38...,"IT분야 직무채용관, DBA·데이터베이스, 데이터베이스, DBA, DW, SQL, ..."
2,텐바이텐 채용 - [텐바이텐] 데이터 엔지니어 경력직 채용 | 잡코리아,데이터 엔지니어,㈜텐바이텐,NaN,NaN,NaN,NaN,서울 > 종로구,경력(1년이상),https://www.jobkorea.co.kr//Recruit/GI_Read/39...,"IT분야 직무채용관, DBA·데이터베이스, 데이터베이스, DW, 웹프로그래머, Py..."
3,네이버제트 채용 - 데이터 엔지니어 모집 | 잡코리아,데이터 엔지니어,네이버제트,"담당업무\nㆍ제페토의 핵심 데이터 수집, 활용 정책 수립\nㆍ제페토의 정형 비정형 ...",모집분야 및 자격요건\n데이터 엔지니어\n자격요건\nㆍ관련 분야 개발 경력 3년 이...,우대사항\nㆍ대용량 / 실시간 데이터 처리 아키텍쳐 구축 경험이 있는 분\nㆍ클라우...,NaN,경기 > 성남시 분당구,경력,https://www.jobkorea.co.kr//Recruit/GI_Read/39...,"IT분야 직무채용관, IT·솔루션·기술영업, 웹사이트구축영업, 네트워크·서버·보안,..."
4,삼성웰스토리 채용 - B2B 온라인(E커머스) 및 Data 부문 경력사원 채용 (데...,데이터 엔지니어,삼성웰스토리㈜,"담당업무\nㆍ데이터 품질 관리\n- 핵심 Data 수집 정책 수립, DB 품질 관리...",모집분야 및 자격요건\n데이터 엔지니어\n자격요건\nㆍ데이터 가공 및 분산 처리 기...,"우대사항\nㆍ컴퓨터공학, AI, SW, 산업공학 등 관련 전공\nㆍAWS SageM...",NaN,경기 > 성남시 분당구,경력,https://www.jobkorea.co.kr//Recruit/GI_Read/39...,"IT분야 직무채용관, 외식 직무채용관, 빅데이터·AI(인공지능), Python, 데..."

In [3]:
remove_rows = []
for i in df.index:
    if df['cname'][i] == 'None':
        remove_rows.append(i)
df.drop(remove_rows, inplace=True)

In [6]:
print (len(df))
print (df.groupby('job')['title'].count())

1405
job
DBA            200
IoT            100
데이터 분석가        113
데이터 사이언티스트      50
데이터 엔지니어       100
데이터 플랫폼 개발자    100
마켓팅 데이터          9
머신러닝 엔지니어      199
백엔드            200
임베디드           100
정보보안           100
풀스택            134
Name: title, dtype: int64

In [7]:
import openpyxl
df.to_excel('../output/Jobkorea_0725_2.xlsx')